[package]
name = "sozu-command-lib"
description = "configuration library to command a sozu instance"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu-command-lib"
homepage = "https://sozu.io"
version = "0.15.16"
license = "LGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition = "2021"
rust-version = "1.70.0"
include = [
  "./README.md",
  "Cargo.toml",
  "src/**/*",
  "assets/certificate.pem",
  "assets/key.pem",
  "assets/404.html",
  "assets/503.html",
]

[dependencies]
hex = "^0.4.3"
libc = "^0.2.149"
log = "^0.4.20"
time = "^0.3.29"
toml = "^0.8.2"
memchr = "^2.6.4"
mio = { version = "^0.8.8", features = ["os-poll", "net"] }
nix = { version = "^0.27.1", features = ["socket", "uio"] }
nom = "^7.1.3"
prost = "^0.12.1"
rand = "^0.8.5"
serde = { version = "^1.0.188", features = ["derive"] }
serde_json = "^1.0.107"
sha2 = "^0.10.8"
trailer = "^0.1.2"
pool = "^0.1.4"
poule = "^0.3.2"
thiserror = "^1.0.49"
x509-parser = "^0.15.1"

[features]
unstable = []
logs-debug = []
logs-trace = []

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }

[build-dependencies]
prost-build = { version = "^0.12.1" }
