name: dagger
on:
  push:
    branches: [dagger]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'
      
      - name: Install python requirements
        run: pip install dagger-io

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
      
      - name: Run Dagger pipeline
        run: dagger run python test.py